#!/bin/bash
BINPATH=`cd "$(dirname "$0")";pwd`
#DATAPATH=${BINPATH}"/data"
DATAPATH="/tmp/.box_info.yml"
LOCAL_IP=$(hostname -i)
IP_PREFIX=$(cut -d . -f1-3 <<<$LOCAL_IP)
GATE_WAY="$IP_PREFIX.1"
BOX_IP=$LOCAL_IP
BOX_NIC=""

function get_gateway()
{
 local gateway=$(ip route get 10.212.0.231|sed 's/.*via\s\(.*\).*dev.*/\1/;tx;d;:x' 2>/dev/null)
 [[ -n $gateway ]] && echo "$gateway" || return 1
}

function del_route()
{
 if  grep -q "src $BOX_IP" <(ip route) ;then 
 route del -net 10.0.0.0 netmask 255.0.0.0 gw $GATE_WAY dev $BOX_NIC 2>/dev/null || return 1
 fi
}
function del_ip_alias()
{
 if  grep -q "$BOX_NIC" <(ifconfig);then 
 ifconfig $BOX_NIC  $BOX_IP netmask 255.255.255.0  down 2>/dev/null || return 1
 fi
}

BOX_IP=$(awk '/box_ip/{print $2}' $DATAPATH  2>/dev/null)
BOX_NIC=$(awk '/box_nic/{print $2}' $DATAPATH  2>/dev/null)
GATE_WAY=$(get_gateway)
del_route
del_ip_alias

